#!/usr/bin/python
 # -*- coding: utf-8 -*-
from subprocess import Popen, PIPE

DBG = False
PATH_TO_BINARY = "./nbProject/GL/dist/Debug/GNU-Linux-x86/gl"

# package things
def execute_shell_and_get_stdout(shell_command, args_list):
	if DBG:
		print "Going to execute command: ", shell_command, args_list
	command = [shell_command]
	command.extend(args_list)
	return Popen(command, stdout=PIPE).communicate()[0]

# CLI things
if __name__ == '__main__':
	from optparse import OptionParser
	parser = OptionParser()
	parser.usage = "usage: %prog [options] fichier_xml"
	parser.add_option("-d", "--dtd", dest="dtd", default=None,
	                  help="Specifie le chemin du fichier DTD. Cela remplacera le fichier DTD specifie dans le fichier XML si il y en a un.", metavar="fichier_dtd")
	parser.add_option("-x", "--xsl", dest="xsl", default=None,
	                  help="Specifie le chemin du fichier DTD. Cela remplacera le fichier DTD specifie dans le fichier XML si il y en a un.", metavar="fichier_xsl")
	(options, args) = parser.parse_args()

	if DBG:
		print options
		print args

	if len(args) != 1:
		parser.print_help()
		exit()

	args2 = [args[0]]

	if options.dtd:
		args2.append(options.dtd)
	if options.xsl:
		args2.append(options.xsl)
	
	print execute_shell_and_get_stdout(PATH_TO_BINARY, args2)



