#!/usr/bin/python
 # -*- coding: utf-8 -*-

DBG = True

from optparse import OptionParser
parser = OptionParser()
parser.usage = "usage: %prog [options] fichier_xml"
parser.add_option("-d", "--dtd", dest="dtd",
                  help="Specifie le chemin du fichier DTD. Cela remplacera le fichier DTD specifie dans le fichier XML si il y en a un.", metavar="fichier_dtd")
parser.add_option("-x", "--xsl", dest="xsl",
                  help="Specifie le chemin du fichier DTD. Cela remplacera le fichier DTD specifie dans le fichier XML si il y en a un.", metavar="fichier_xsl")
(options, args) = parser.parse_args()

if DBG:
	print options
	print args

if len(args) != 1:
	parser.print_help()