#!/usr/bin/python
# -*- coding: utf-8 -*-

import unittest

from pyutils.xsl_tests import XSLTest
if __name__ == '__main__':
    suite = unittest.TestSuite()

    for i in xrange(1, 10):
        suite.addTest(XSLTest("test_simple" + str(i)))
    for i in xrange(1, 4):
        suite.addTest(XSLTest("test_complex" + str(i)))
    unittest.TextTestRunner().run(suite)
